server:
  port: 5555

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/returnorder
      
#        native:
#          searchLocations: file://${user.home}/returnorder

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false